### PR TITLE
feat: add team colors as RGB color lists

### PR DESCRIPTION
**Pull request by firstof9**
* fix: broken reconfigure flow
* formatting
* add extra typing
* rename DataCoordinator class to NFLDataUpdateCoordinator

### CODE REVIEW

**Comment by zacs** [comment]
Can't check code atm, but is the colors list checkin backcompat?

**Comment by firstof9** [comment]
What do you mean?
Rather than dumping the HEX it dumps it in RGB list form so you can consume it in Home Assistant easier.

**Comment by zacs** [comment]
Right, so anyone relying on the hex value will break. I'd like to avoid making breaking changes unless there's significant added value. If you can revert that one commit, the rest look fine and I can merge. Thanks!

**Comment by zacs** [comment]
Alternatively I'm happy to take the new rgb values if you just give them a new property name like teamcolors_rgb and leave the hex as it is. Your call!

**Comment by firstof9** [comment]
Ok, I can make it a new attribute

**Comment by gonzotek** [comment]
Thanks for adding it as a new property.  I had created an automation+script+rest_command that ultimately calls a WLED device with the hex values of the team colors, so if they weren't available, I'd just be converting back from RGB to HEX (because I really like seeing the strip light up with the team/opponent colors when I'm following a couple games at once on Sundays).  But I can also see value in having them in RGB as well, since HA lights will consume them more easily, and that's what most people will want to do.

**Comment by firstof9** [comment]
It also opens it up easier for other service calls such as `light.turn_on` for other RGB lights as well.

**Comment by zacs** [comment]
Nice, thanks for the quick turnaround and appreciate the flexibility. You are brave to try linting my late night code 😂 .

**Pull request merged**
