### PR TITLE
Update hacs.json to render the repository readme

### PR DESCRIPTION
**Pull request by gonzotek**
Tell hacs to use readme.md instead of using info.md, which is outdated.  Fixes https://github.com/zacs/ha-nfl/issues/24

### CODE REVIEW

**Comment by firstof9** [comment]
I'd also remove the `info.md` in this PR too

**Comment by gonzotek** [comment]
> I'd also remove the `info.md` in this PR too

Thanks for the tip!  Looking at the hacs developer site, think there's some more that can be changed/improved in hacs.json, but I need more time to read up on it first.

**Comment by gonzotek** [comment]
Hmm...something's wrong.  I checked the info popup in hacs this morning and the readme wasn't showing.  If I remove the @zacs fork and add mine, I do get the expected info from the readme.md. Swapping back to the zacs fork and it's gone again. One difference I see is my fork has no releases...since the zacs fork has used releases previously, could hacs need a new release before it'll pick up the change to hacs.json?  Sorry for any extra work @zacs, I know you're busy and was trying to keep any maintenance work easy on you.

BTW, on a slightly related note.. I was thinking of looking into what it would take to have hacs pick up the integration in its default repositories (vs requiring the user to add as a custom repository), if that's something you'd want?

**Comment by zacs** [comment]
Yah the release issue is be design -- basically I think HACS defaults to latest release if there are any. I was just planning to not cut a release for something this small (and include it in a later release). 

As far as general addition to HACS I would love that. I think it would just be a one liner to the HACS integration list?

**Comment by gonzotek** [comment]
No worries, I was hoping it wasn't something I'd done wrong (again) and just a matter of the releases.  Whenever you feel it's worth it!

As far as adding to HACS, I'm going by these two links(in particular, the second one includes some details about an integration manifest, some github actions, and some organizational requirements that all might need to be addressed):
https://hacs.xyz/docs/publish/start
https://hacs.xyz/docs/publish/include

I'll work through the requirements via my fork then submit PRs and/or issues for everything when I think I have a good enough handle on it all.  Might be a couple weeks or a bit more.

**Pull request merged**
